# Apply Trained Models to External Data

This file illustrates how to reuse the text classification models on data of your choice.

### Table of Contents

**I. Preprocessing**
* Select descriptions to include as input text for gender biased text classification
* Tokenize the text

**II. Feature Extraction**
* Represent tokens as word embeddings with the custom FastText word embedding model
* Represent descriptions as TFIDF matrices

**III. Classification**
* Linguistic Classifier > Stereotype & Omission Classifier (Cascade 2)
* Stereotype & Omission Classifier (Baseline)
* Gendered Pronoun & Gendered Role Classifier > Stereotype & Omission Classifier
* Person & Occupation Classifier > Stereotype & Omission Classifier

Import programming libraries:

In [9]:
# Custom filepaths and functions
import config, my_utils

# Libraries for data, file, and model loading
import pandas as pd
import joblib
import os, re
import numpy as np
from pathlib import Path

# Libraries for classification
import scipy
import sklearn.metrics
from skmultilearn.problem_transform import ClassifierChain
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import SGDClassifier

## I. Preprocessing

Specify the path to your data, which is expected to be in a CSV file.  One column of the CSV file should be for the text that you want to classify, where each row has a unique text entry.

In [ ]:
f = "" # insert your data's file path here

Load the data as a pandas DataFrame, adding a column called `record_id` that creates a unique identifier for each row of the DataFrame.

In [8]:
df = my_utils.loadCSVData(f, False)
df.head()

,record_id,Unnamed: 0,description_id,start_offset,end_offset,field,description,subset,label,fold
0,0,0,4699,1853,2066,Biographical / Historical,"Labelled Apparently some chapters, amounting t...",train,['Omission'],split3
1,1,1,8942,384,540,Biographical / Historical,James Aikman of Perth signed his name to a vol...,train,[''],split2
2,2,2,5440,5692,5850,Biographical / Historical,This piece was published in 'Milk Production i...,train,[''],split0
3,3,3,3474,3608,8549,Biographical / Historical,Margaret Winifred Bartholomew was born on 21 A...,train,"['Omission', 'Stereotype']",split0
4,4,4,4769,2378,2576,Biographical / Historical,Blacker and Thomson became close friends throu...,train,['Omission'],split3

Specify the column(s) with the text that you want to classify.

In [ ]:
text_cols = ""  # For example: "Description"

Tokenize the data and create a new DataFrame that has one token (a.k.a. a word, subword, or punctuation mark) per row, assigning each token a unique identifier in a `token_id` column.

In [ ]:
token_df = my_utils.getTokenDF(df, text_cols)
token_df.tail()

     record_id token_id      token
133        137     1737          .
134        138     1738  Telephone
134        138     1739     number
134        138     1740         46
134        138     1741          .

## II. Feature Extraction

Load the MultiLabelBinarizer for the Linguistic Classifier.

In [ ]:
print(my_utils.mlb_ling.classes_)  # Prints the names of labels that this MultiLabelBinarizer represents as 0 or 1

['Gendered-Pronoun' 'Gendered-Role' 'Generalization']

Load the MultiLabelBinarizer for the Omission and Stereotype Classifier.

In [ ]:
print(my_utils.mlb_so.classes_) # prints the names of labels that this MultiLabelBinarizer represents as 0 or 1

['Omission' 'Stereotype']

Represent the Linguistic Classifier's input data as embeddings using the custom, 100 dimension fastText embeddings trained on University of Edinburgh archival data.

In [ ]:
embedding_matrix = my_utils.getFeatures(token_df)

Represent the Omission and Stereotype Classifier's input data as a TF-IDF matrix.

In [ ]:
tfidf_matrix = my_utils.docToTfidf(df, text_cols)

## III. Classification

### Linguistic Classifier
* Type: Multilabel token classification
* Targets: Gendered Pronoun, Gendered Role, Generalization

Create a new directory to save classified data to.

In [ ]:
classified_data_path = "../data/classified/"
Path(classified_data_path).mkdir(parents=True, exist_ok=True)

Load the trained Linguistic Classifier.

In [ ]:
trained_ling_clf = joblib.load(
    config.models_path+"multilabel_token/cc-rf_F-fasttext100_T-linglabels.joblib"
    )

Run the classifier.

In [ ]:
X = embedding_matrix
y = trained_ling_clf.predict(X)

Save the classified data to a new directory.

In [ ]:
filename = "linguistic_predictions.csv"
ling_pred_col = "predicted_linguistic"
token_df = my_utils.exportClassifiedData(
    token_df, y, my_utils.mlb_ling, classified_data_path, filename, ling_pred_col
    )
token_df.head()

   record_id token_id      token prediction
0          0        0    Wedding         []
0          0        1  Greetings         []
0          0        2          (         []
0          0        3    General         []
0          0        4          )         []

Count the number of times a token was classified with one of the three Linguistic labels.

In [ ]:
token_df[ling_pred_col].value_counts()

[]                  1739
[Gendered-Role]        2
[Generalization]       1
Name: prediction, dtype: int64

### Omission and Stereotype Classifier
* Type: multilabel document classification
* Targets: Omission, Stereotype
* Optional Features: labels assigned by the Linguistic Classifier

Uncomment one of the two following code cells below to preprocess the data.

In [ ]:
'''
If you are running a baseline Omission and Stereotype Classifier, meaning you are not 
using Linguistic Classifier's labels as features, uncomment this cell's code.
'''
# doc_df = df
# trained_so_clf = joblib.load(config.models_path+"multilabel_document/sgd-svm_F-tfidf_T-os.joblib")
# doc_df = my_utils.preprocessClassifiedDocs(df, token_df)
# doc_df = doc_df.fillna("")
# vectorized = my_utils.cvectorizer.transform(doc_df[text_col])
# X = my_utils.tfidf.transform(vectorized)

# filename = "baseline_os_predictions.csv"

,record_id,document_prediction,RecordType,AltRefNo,RefNo,Title,Original Date Field,Description,RelatedNameCode,Authority Type,Authority Name
0.0,0,[],Photograph,TCD 263/MUS 1079,BTA/5 PH/7/MUS 1079,Wedding Greetings (General),NaN,Image of telegram.,NaN,NaN,NaN
1.0,1,[],Photograph,TCD 263/MUS 1142,BTA/5 PH/7/MUS 1142,Baby (Blanket and tag design),NaN,Image of telegram.,NaN,NaN,NaN
2.0,2,[],Photograph,TCD 263/MUS 1075,BTA/5 PH/7/MUS 1075,Wedding (General Greeting),NaN,Image of telegram.,NaN,NaN,NaN
3.0,3,[],Photograph,TCD 263/MUS 977,BTA/5 PH/7/MUS 977,Ordinary,NaN,Designer/manufacturer: Perry,NaN,NaN,NaN
4.0,4,[Generalization],Photograph,TCD 263/MUS 637,BTA/5 PH/7/MUS 637,Two girls sending telegraph message,c1910,NaN,NaN,NaN,NaN

In [ ]:
'''
Alternatively, if you are using the Linguistic Classifier's labels as features, 
uncomment this cell's code instead.
'''
# trained_so_clf = joblib.load(config.models_path+"multilabel_document/sgd-svm_F-tfidf-ling_T-os.joblib")
# doc_df = my_utils.preprocessClassifiedDocs(df, token_df, ling_pred_col)
# features = my_utils.mlb_ling.transform(doc_df[ling_pred_col])
# doc_df = doc_df.fillna("")
# vectorized = my_utils.cvectorizer.transform(doc_df[text_col])
# docs = my_utils.tfidf.transform(vectorized)
# X = scipy.sparse.hstack([docs, features])

# filename = "ling_os_predictions.csv"

Run the Omission and Stereotype Classifier.

In [ ]:
y_pred = trained_so_clf.predict(X)

Transform the classified data and add it to the DataFrame.

In [ ]:
pred_labels = my_utils.mlb_so.inverse_transform(y_pred)
print(pred_labels[:100])

[(), (), (), (), (), ('Omission', 'Stereotype'), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), ('Stereotype',), (), (), (), (), (), (), (), (), (), (), (), (), (), (), ()]

In [ ]:
pred_col_name = "predicted_os"

In [ ]:
new_pred_col = []
for values in pred_labels:
    preds = []
    if (values != [tuple()]) and (values != []):
        for t in values:
            if len(t) > 0:
                label = str(t).strip("(',)")
                if label not in preds:
                    preds += [label]
    new_pred_col += [preds]
print(new_pred_col[:100])
doc_df.insert(len(doc_df.columns), pred_col_name, new_pred_col)
doc_df.head()

[[], [], [], [], [], ['Omission', 'Stereotype'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Stereotype'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]

,token_id,token,predicted_linguistic,Title,predicted_so
record_id,,,,,
0,"[0, 1, 2, 3, 4]","[Greetings, Wedding, (, ), General]",[],Wedding Greetings (General),[]
1,"[5, 6, 7, 8, 9, 10, 11]","[tag, (, Baby, ), Blanket, design, and]",[],Baby (Blanket and tag design),[]
2,"[12, 13, 14, 15, 16]","[Greeting, Wedding, (, ), General]",[],Wedding (General Greeting),[]
3,[17],[Ordinary],[],Ordinary,[]
4,"[18, 19, 20, 21, 22]","[girls, Two, telegraph, sending, message]",[Generalization],Two girls sending telegraph message,[]

In [ ]:
doc_df[pred_col_name].value_counts()

[]                        69382
[Omission, Stereotype]        1
[Stereotype]                  1
Name: predicted_so, dtype: int64

Save the classified data.

In [ ]:
doc_df.to_csv(classified_data_path+filename)